version: '3.8'

services:
    db:
        image: postgres:16-alpine
        container_name: tinyurl-db
        environment:
            POSTGRES_DB: urlshortener
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: gangadhar
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d urlshortener"]
            interval: 5s
            timeout: 5s
            retries: 10

    app:
        build: .
        container_name: tinyurl-app
        depends_on:
            db:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: gangadhar
        ports:
            - "8080:8080"

volumes:
    pgdata: