apiVersion: v1
kind: Service
metadata:
  name: tinyurl-service
spec:
  selector:
    app: tinyurl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # For local access; use LoadBalancer if Minikube supports